name: Ubuntu 24.04 CI

on: [push, pull_request]

jobs:
  ubuntu-build:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v5
      - name: Use cmake
        run: |
          mkdir build &&
          cd build &&
          cmake -DFASTFLOAT_CXX_STANDARD=20 -DFASTFLOAT_TEST=ON -DCMAKE_INSTALL_PREFIX:PATH=destination ..  &&
          cmake --build .   &&
          ctest --output-on-failure  &&
          cmake --install .
